/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'afahie' at '27/06/16 21:30' with Gradle 2.14
 *
 * @author afahie, @date 27/06/16 21:30
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
